# what is the goal of your workflow

#GOAL - whenever someone changes the python code, the linter will check if the syntax format indentation (linting) is correct or not. 

name: Auto Linter

on: 
  push:
    paths: "*.py"

jobs:
  code-linting:
    runs-on: ubuntu-latest
    
    #this step will auto clone the code of the current branch into runner.
    steps:
      - name: checkout/clone the code
        uses: actions/checkout@v7

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
        
    #this step will install linting tool
      - name: Install linter
        run: pip install ruff
        
    # this step will run the linter
      - name:  check the files for linting
        run: ruff check .
